---
language: ruby
os:
  - linux
  - osx
jobs:
  include:
    - os: linux
      dist: focal
    - os: osx
cache: bundler
rvm:
  - 2.7.0
  - 2.6.5
  - 2.5.5
  - 2.3.1
addons:
  apt:
    update: true
before_install:
  - gem install bundler -v 2.1.4
install:
    - ./.travis/install.sh    
script: bundle exec rake