---
language: ruby
os:
  - linux
  - osx
dist: focal
compiler:
  - clang
  - gcc
cache: bundler
rvm:
  - 2.7.0
  - 2.6.5
  - 2.5.5
addons:
  apt:
    update: true
before_install:
  - gem install bundler -v 2.1.4
install:
    - ./.travis/install.sh 
    - bundle install
script: bundle exec rake